- name: Deploiement de l'application en staging et en prod
  hosts: all
  become: true
  vars:
    app_image: "nadhemo/pageturner_img:latest"
    container_name: "dico-app"
    app_port: 8080
  tasks:
    - name: Verification que Docker est bien installé
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Pull de la dernière image docker de l'app
      docker_image:
        name: "{{ app_image }}"
        source: pull

    - name: Stop un eventuel container en cours d'execution
      docker_container:
        name: "{{ container_name }}"
        state: stopped
        force_kill: yes
      ignore_errors: yes

    - name: Supression d'un container
      docker_container:
        name: "{{ container_name }}"
        state: absent
      ignore_errors: yes

    - name: Deploiment du container de l'app
      docker_container:
        name: "{{ container_name }}"
        image: "{{ app_image }}"
        state: started
        restart_policy: always
        ports:
          - "{{ app_port }}:{{ app_port }}"